name: vk_video
description: "The vk_video package simplifies the integration of VK video playback into your Flutter apps. It supports the VK Video API, allowing easy embedding and control for a seamless media experience."
version: 0.0.1
repository: https://github.com/ultra-rony/vk_video
homepage: https://rony.fun

topics: [vk, vk_video, player, video]

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: The logo of the vk_video package.
    path: screenshots/logo.png
