name: vk_video
description: "The vk_video package provides a simple and efficient way to integrate VK Video playback into your Flutter applications. With support for the VK Video API, this package allows you to easily embed and control VK videos, enabling seamless media experiences within your app."
version: 0.0.1
repository: https://github.com/ultra-rony/vk_video
homepage: https://rony.fun

topics: [vk, vk-video, player, video]

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
