name: rutube_video
# description: "The rutube_video package facilitates Rutube video playback integration in Flutter apps, supporting the Rutube Video API for seamless embedding and control."
# version: 1.0.4
# repository: https://github.com/ultra-rony/rutube_video
# homepage: https://rony.fun

# topics: [rutube, rutube-video, player, video]

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# screenshots:
#   - description: The logo of the rutube_video package.
#     path: screenshots/logo.png
